service: serverless-lambda-exercise

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-south-1

functions:
  countItemsInS3Bucket:
    handler: index.countItemsInS3Bucket
    name: count-items-in-s3-bucket
